# Generated by Django 2.2.5 on 2019-09-10 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='scraped_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 10, 19, 4, 46, 274144)),
        ),
    ]
