# Generated by Django 2.2.4 on 2019-09-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
