# Generated by Django 2.2.5 on 2019-09-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_flat_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='scraped_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
