# Generated by Django 2.2.5 on 2019-09-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_auto_20190910_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='scraped_date',
            field=models.DateTimeField(default=None),
        ),
    ]
