# Generated by Django 2.2.4 on 2019-09-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_pages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
