# Generated by Django 2.2.4 on 2019-09-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_auto_20190904_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('ip', models.CharField(max_length=70, primary_key=True, serialize=False)),
            ],
        ),
    ]
